wenghaishi/catch-1160

Gemfile.lock
app/models/business.rb
app/models/capture.rb
app/models/catch.rb
app/models/collection.rb
app/models/token.rb
app/models/user.rb
db/migrate/20230320084004_add_colums_to_users.rb
db/migrate/20230320084818_create_businesses.rb
db/migrate/20230320085054_create_collections.rb
db/migrate/20230320085328_create_tokens.rb
db/migrate/20230320085524_create_catches.rb
db/migrate/20230320085626_add_reference_column_to_users.rb
db/migrate/20230320100442_rename_catchto_capture.rb
db/schema.rb
test/models/business_test.rb
test/models/catch_test.rb
test/models/collection_test.rb
test/models/token_test.rb

Created all models and added validations and associations

14 create models and add validations and associations

---

pull_request_template.md

​
Added template for Pull Requests.
​
Fixes #18  (issue)
​
​
​
​

add pull request template

---

app/models/collection.rb
db/migrate/20230321031352_add_columns_to_collection.rb
db/schema.rb

​
Added description, category columns to collection
Added photo and banner association to collection.
​
Fixes # (added attributes to collection)
​
​
​
​
​
​

19 add additional columns to the collection class

---

db/migrate/20230321045515_add_description_column_to_business.rb
db/migrate/20230321045713_add_banner_url_column_to_users.rb
db/schema.rb

​business can add a description and users has a banner url
​
Fixes # (business has no description and users have no banner)
​
​
​
​
​

Add description to business model & add banner url to users model

---

db/migrate/20230320084004_add_colums_to_users.rb
db/migrate/20230320084818_create_businesses.rb
db/migrate/20230320085328_create_tokens.rb
db/migrate/20230321031352_add_columns_to_collection.rb
db/migrate/20230321032415_add_img_url_to_token.rb
db/migrate/20230321045515_add_description_column_to_business.rb
db/migrate/20230321045713_add_banner_url_column_to_users.rb
db/schema.rb

​
removed default = "false" from all models
Fixes # (model validations will not work because of default)
​
​
​
​
​

removed default from all models

---

app/javascript/controllers/map_controller.js
db/schema.rb

​
Added function to load the map with the user's current location, setting pitch and zoom.
​
Fixes #25  (issue)
​
​
​
​
​
​
​

Added function to load map with user's current location

---

db/migrate/20230320084004_add_colums_to_users.rb
db/migrate/20230320084818_create_businesses.rb
db/migrate/20230320085328_create_tokens.rb
db/migrate/20230321031352_add_columns_to_collection.rb
db/migrate/20230321032415_add_img_url_to_token.rb
db/migrate/20230321045515_add_description_column_to_business.rb
db/migrate/20230321045713_add_banner_url_column_to_users.rb
db/schema.rb

Reverts wenghaishi/catch-1160#27
Bali is a dumbass

Revert "removed default from all models"

---

db/migrate/20230321081203_remove_default_from_models.rb
db/schema.rb

​
removed default attribute from models
​
Fixes # (models have default attached to their attributes)
​
​
​
​
​
​

removed default from models

---

db/schema.rb
db/seeds.rb

​
Edit seed data: Token addresses should return a longitude and latitude using geocoder.
​
Fixes #38  (issue)
​
​
​
​
​
Tested in rails console on my machine.
​
​
​

edit address for tokens in seed file

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/components/_popup.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/controllers/tokens_controller.rb
app/javascript/controllers/map_controller.js
app/views/tokens/_info_window.html.erb
app/views/tokens/_marker.html.erb
app/views/tokens/index.html.erb

​
Added popup when clicking on a token's marker.
​
Fixes #1  (issue)
​
​
​
​
​
​
​

1 task create map on landing page that displays all nfts near user

---

app/assets/stylesheets/components/_popup.scss
app/javascript/controllers/map_controller.js
app/views/tokens/_info_window.html.erb

​
Removed compass direction bearing on mapbox.
​
Fixes #46  (issue)
​
​
​

removed compass bearing on mapbox

---

app/assets/stylesheets/components/_banner.scss
app/controllers/users_controller.rb
app/views/users/show.html.erb

​
Created a user profile page that displays all nfts owned by that user
​
​
​
​
​

Created user profile page

---

app/controllers/application_controller.rb
app/controllers/biz/businesses_controller.rb
app/controllers/biz/users_controller.rb
app/controllers/biz_controller.rb
app/controllers/collections_controller.rb
app/controllers/pages_controller.rb
app/controllers/tokens_controller.rb
app/controllers/user_controller.rb
app/controllers/users_controller.rb
app/views/biz/businesses/me.html.erb
app/views/biz/businesses/new.html.erb
config/routes.rb

​
added biz namespace, where business users have their own specific route and users has their own
​
Fixes # (authentication)
​
​
​
​
​

refactor biz namespace

---

app/controllers/application_controller.rb
app/controllers/biz/collections_controller.rb
app/controllers/biz/tokens.rb
app/controllers/biz/tokens_controller.rb
app/controllers/pages_controller.rb
app/views/biz/businesses/show.html.erb
app/views/biz/collections/new.html.erb
app/views/biz/tokens/new.html.erb
app/views/collections/show.html.erb
app/views/users/show.html.erb
config/routes.rb

​
Please include a summary of the changes and the link to the ticket (jira/canban board etc). Please also include relevant motivation and context. List any dependencies that are required for this change.
​
​
​
​
​
​
​
​
​

[IN PROGRESS]

---

app/assets/stylesheets/components/_button.scss
app/controllers/tokens_controller.rb
app/javascript/controllers/map_controller.js
app/views/layouts/application.html.erb
app/views/tokens/_info_window.html.erb

​
Display catch button on a token when user is close enough. Button is disabled if they are not close enough.
​
Fixes #50  (issue)
​
​
​
​
​
​

50 task user can only catch a token if location is close enough

---

app/assets/stylesheets/application.scss
app/views/devise/registrations/new.html.erb
config/environments/production.rb

​
trying to fix heroku background not showing
​
​
​
​
​
​
​
​
​

fixing heroku problem

---

app/javascript/controllers/map_controller.js

​
Remove user tracking on map.
​
Fixes #67  (issue)
​
​
​
​

fixed map locator

---

app/models/token.rb
app/views/tokens/_info_window.html.erb
db/migrate/20230324063014_add_number_to_tokens.rb
db/schema.rb

​
New migration to add 
​
Fixes #71  (issue)
​
​
​
​
​

new migration to add :identifier to tokens

---

app/controllers/biz/businesses_controller.rb
app/views/biz/businesses/show.html.erb
app/views/users/show.html.erb

​
all show pages will now use token identifier attribute instead of token index
​
​
​
​
​

change show pages to use token identifier

---

app/controllers/biz/businesses_controller.rb
app/controllers/biz/tokens_controller.rb
app/controllers/pages_controller.rb
app/views/biz/businesses/show.html.erb
app/views/biz/tokens/_info_window.html.erb
app/views/biz/tokens/_marker.html.erb
app/views/biz/tokens/index.html.erb
config/routes.rb

​
Added map view for a business to see all their tokens on the map.
Fixes #76  (issue)
​
​
​
​

76 create map index to show a businesses tokens

---

app/javascript/controllers/map_controller.js
app/views/layouts/application.html.erb

​
Display route to a Token marker when it is clicked. Set bearing to point towards the marker. 
​
Fixes #80  (issue)
​
​
​
​
​

80 display route to a marker when clicked

---

app/assets/stylesheets/components/_alert.scss
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb

​edited alert pop up to fade away after a given time and changed the size 
​
​
​
​

changed alert pop up

---

app/views/tokens/_info_window.html.erb
app/views/users/show.html.erb

​
Added link on marker popup to redirect to a business' profile.
​
Fixes #104  (issue)
​
​
​
Tested on my machine.
​
​
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have added proof(eg. screenshots) that prove my fix is effective or that my feature works

added link on marker popup to redirect to business profile

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_marker.scss
app/views/tokens/_marker.html.erb

​
Added glow effect on markers.
​
​
​
​
​
​

add glow on markers

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_banner.scss
app/controllers/biz/collections_controller.rb
app/controllers/biz/tokens_controller.rb
app/javascript/controllers/address_autocomplete_controller.js
app/javascript/controllers/index.js
app/javascript/controllers/tokens_controller.js
app/views/biz/collections/new.html.erb
app/views/biz/collections/show.html.erb
app/views/biz/tokens/_form.html.erb
app/views/biz/tokens/_token.html.erb
app/views/biz/tokens/create.json.jbuilder
app/views/biz/tokens/new.html.erb

​
Token creation form now appears on the collection show page, implemented ajax so that new token card will be added on the collection show page after creation, and implemented ajax on the token counter as well
​
​
​
​
​

Token form appears on collection page

---

app/controllers/biz/collections_controller.rb
app/controllers/businesses_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/search_controller.js
app/views/businesses/_businesses.html.erb
app/views/businesses/_header.html.erb
app/views/businesses/index.html.erb

​
businesses show page search bar uses ajax 
​
​
​
​
​
​

Add ajax to search bar

---

app/assets/stylesheets/components/_alert.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_modal.scss
app/javascript/controllers/address_autocomplete_controller.js
app/javascript/controllers/map_controller.js
app/views/tokens/_info_window.html.erb

​
Added modal popup to Catch a Token. Random chance of success or failure.
​
Fixes #87  (issue)
​
​​
​
​
​

87 adding a minigame to the catch mechanism

---

app/views/businesses/_businesses.html.erb
app/views/businesses/show.html.erb
app/views/collections/show.html.erb

​
Added link to Search button when a User views a Business page or collection.
​
Fixes #123  (issue)
​
​
​
​
​
Tested on my machine.
​
​

added link to search when a user views a business page

---

app/assets/images/Plus_active.svg
app/assets/stylesheets/components/_game.scss
app/views/biz/collections/new.html.erb

​
Added footer to New Collection form page.
​
Fixes #136  (issue)
​
​
​
​
​

add footer to new collection form page

---

app/controllers/biz/tokens_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/map_controller.js
app/javascript/controllers/mapbiz_controller.js
app/views/biz/tokens/_info_window.html.erb
app/views/biz/tokens/_marker.html.erb
app/views/biz/tokens/_markerbiz.html.erb
app/views/biz/tokens/index.html.erb

​
Added a different map view for when a business user logs in.
​
Fixes #139  (issue)
​
​
​
​

added new map view for a business

---

app/assets/stylesheets/application.scss
app/controllers/tokens_controller.rb
app/views/devise/registrations/new.html.erb

​
Please include a summary of the changes and the link to the ticket (jira/canban board etc). Please also include relevant motivation and context. List any dependencies that are required for this change.
​
​
​
​
​
​
​
​
​

added css styling for sign up

---

app/views/tokens/_info_window.html.erb

fixed map bug

---

app/assets/stylesheets/components/_game.scss

​
Please include a summary of the changes and the link to the ticket (jira/canban board etc). Please also include relevant motivation and context. List any dependencies that are required for this change.
​
​
​
​
​
​
​
​
​

added z-index

---

app/javascript/controllers/map_controller.js

​
Show a wider view of the map when a User loads the map.
​
Fixes #143  (issue)
​
​
​
​
​
​

show more markers when User loads the map

---

app/controllers/tokens_controller.rb
app/views/tokens/_info_window.html.erb
app/views/tokens/_marker.html.erb

​
Display token markers as photos.
​
Fixes #62  (issue)
​
​
​
​
​
​
​

display token images as markers on the map

---

app/views/biz/businesses/show.html.erb
app/views/biz/tokens/_token.html.erb
app/views/businesses/show.html.erb
app/views/collections/show.html.erb
app/views/tokens/_info_window.html.erb
app/views/users/show.html.erb

​
Added padding to the category on the token card
​
​
​
​
​
​
​

Add padding to token category 

---

app/controllers/tokens_controller.rb
app/views/tokens/show.html.erb
db/migrate/20230330084118_addtokenurl_to_tokens.rb
db/schema.rb
db/seeds.rb

​
Please include a summary of the changes and the link to the ticket (jira/canban board etc). Please also include relevant motivation and context. List any dependencies that are required for this change.
​
​
​
​
​
​
​
​
​

added column of token

---

app/views/tokens/show.html.erb

​
Added consistent footer for token show page.
​
Fixes #160  (issue)
​
​

added consistent footer for token show page

---

app/views/biz/collections/new.html.erb

​
Added more categories for Collection creation.
​
​
​
​
​
​

add categories for collection creation page

---

db/seeds.rb

removed pizza tokens from seed file
​
​
​
​
​
​

removed pizza token from seed
